### ISSUE TITLE
Graph vtk files in data preparation

### ISSUE THREAD

**Issue by sean-xr** [chinmay5/vesselformer#1]
Hello chinmay, Thanks for your great work! I was trying to run your code, but I have some doubt regarding the data preparatio step:
We're supposed to download the data and arrange them in this way: 
code_root/
└── data/
    └── vessel_data/
        ├── raw/
        ├── seg/
        └── vtk/

However, when I checked the three folders, raw/ and seg/ each contains 136 nifti files, while vtk/ contains 9 subfolders, each contains the same "1_artery_final" 1-16 vtk files. So for the data preparation step, which of these sub-folders should I use? 

Thanks for the answer in advance!

**Comment by chinmay5** [comment]
Please download the vtk files from [here](https://filesender.switch.ch/filesender2/?s=download&token=60b053a1-c7c7-4de9-8d14-c84ca77d5077)

**Comment by sean-xr** [comment]
> Please download the vtk files from [here](https://filesender.switch.ch/filesender2/?s=download&token=60b053a1-c7c7-4de9-8d14-c84ca77d5077)

Hi Chinmay, thanks for the answer! Now the training set can be successfully generated.

**Comment by Erolf345** [comment]
Hi Chinmay,

I am also facing this issue and your link has expired. Can I also find the vtk files in the deepvesselnet repo?

EDIT:
Nevermind, I just had to extract the files to the main directory like this:

```

import os

SRC_DIR = r"data\vessel_data\vtk"
TARGET_DIR = r"data\vessel_data\vtk"

counter = 1
dirs = [f for f in os.listdir(SRC_DIR) if os.path.isdir(os.path.join(SRC_DIR, f))]

for d in dirs:
    tmp_src = os.path.join(SRC_DIR, d)
    src_files = [f for f in os.listdir(tmp_src) if ".vtk" in f]

    for f in src_files:
        src = os.path.join(tmp_src, f)
        dst = os.path.join(TARGET_DIR, str(counter) + ".vtk")
        print(src, " -> ", dst)
        os.rename(src, dst)
        counter += 1
```

**Comment by chinmay5** [comment]
Here is the new link to the dataset. Please feel free to reopen the issue if there is a problem with the code or the link.
[link](
https://syncandshare.lrz.de/getlink/fiAsdfoE9ohy5DwcxDkbYp/vtp_files.tar)
